name: build-n60
on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-23.05
  REPO_BRANCH: openwrt-23.05
  CONFIG_FILE: n60_config
  REPO_NAME: immortalwrt-mt798x-23.05
  DTS_PATH: target/linux/mediatek/files-5.4/arch/arm64/boot/dts
  FIRMWARE_NAME: IB
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1.下载config配置
        uses: actions/checkout@main

      - name: 2.安装依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5 \
          libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lld llvm lrzsz mkisofs msmtp \
          nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip python3-ply \
          python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo apt install -y jq
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "=========gcc --version========="
          gcc --version

      - name: 4.初始化仓库
        working-directory: /workdir
        run: |
          df -hT $PWD
          echo "Using branch: $REPO_BRANCH"
          git clone -b $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL 
          ln -sf /workdir/$REPO_NAME $GITHUB_WORKSPACE/$REPO_NAME
          cd $REPO_NAME
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 5.自定义固件
        working-directory:
        run: |
          cp hanwckf/n99-AX6000/mt7986a-netcore-n60.dts /workdir/$REPO_NAME/
          cd /workdir/$REPO_NAME
          rm $DTS_PATH/mt7986a-netcore-n60.dts
          mv mt7986a-netcore-n60.dts $DTS_PATH

      - name: 6.加载配置文件
        run: |
          ls -l hanwckf/n99-AX6000/n60_config || echo "Config file not found"
          if [ -e hanwckf/n99-AX6000/n60_config ]; then
            cp -f hanwckf/n99-AX6000/n60_config /workdir/$REPO_NAME/.config
            ls /workdir/$REPO_NAME/
          else
            echo "Config file $CONFIG_FILE not found. Exiting..."
            exit 1
          fi

      - name: 7.修改Lan IP
        run: |
          cd $REPO_NAME
          sed -i 's/192.168.1.1/192.168.29.1/g' package/base-files/files/bin/config_generate

      - name: 8.修改默认主题
        run: |
          cd $REPO_NAME
          sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' feeds/luci/collections/luci/Makefile
          if [ ! -d "package/luci-theme-argon" ]; then
            git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git package/luci-theme-argon
          fi

      - name: 9.下载依赖包
        run: |
          cd $REPO_NAME
          for i in {1..3}; do
            if make download -j$(nproc) V=s; then
              echo "Download successful on attempt $i"
              break
            else
              echo "Download failed on attempt $i, retrying..."
              sleep 60
            fi
          done
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 10.开始编译
        run: |
          cd $REPO_NAME      
          echo -e "$(nproc) thread compile"
          make -j$(nproc)
          echo "::set-output name=status::success"
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' | sed 's/^_//' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
      - name: 11.Clean IB Releases
        uses: actions/github-script@v6
        with:
          script: |
            const pattern = /^IB-/i;  // 匹配以 immortalwrt-2 开头的名称
            const keep = 0;
  
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
  
            const targets = releases
              .filter(release => pattern.test(release.name))
              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at))
              .slice(keep);
  
            for (const release of targets) {
              await github.rest.repos.deleteRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: release.id,
              });
              console.log(`Deleted IB release: ${release.tag_name}`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 11.上传bin目录
        uses: actions/upload-artifact@master
        with:
          name: amd64_x86
          path: immortalwrt-mt798x-23.05/bin/targets/x86/64/*

      - name: 12.发布N99
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.FIRMWARE_NAME }}-latest"
          artifacts: "immortalwrt-mt798x-23.05/bin/targets/x86/64/*"
          body: |
            N99