name: BuildAmd64
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 16 * *'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  CONFIG_FILE: .config_amd64
  REPO_NAME: immortalwrt
  FIRMWARE_NAME: immortalwrt
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1.获取最新稳定版本
        id: get_version
        run: |
          # 获取所有标签
          TAGS=$(curl -s https://api.github.com/repos/immortalwrt/immortalwrt/tags | jq -r '.[].name')
          # 过滤出稳定版本标签（格式如 v24.10.1）并排序
          LATEST_STABLE=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -rV | head -n1)
          if [ -z "$LATEST_STABLE" ]; then
            echo "No stable version found, using default branch"
            echo "REPO_BRANCH=openwrt-24.10" >> $GITHUB_ENV
          else
            # 提取主要版本号（如 24.10）并去除v前缀
            MAIN_VERSION=$(echo $LATEST_STABLE | sed 's/v\([0-9]\+\.[0-9]\+\).*/\1/')
            echo "REPO_BRANCH=openwrt-$MAIN_VERSION" >> $GITHUB_ENV
            echo "Using branch: openwrt-$MAIN_VERSION based on tag $LATEST_STABLE"
          fi

      - name: 2.下载config配置
        uses: actions/checkout@master

      - name: 3.安装依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt install build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 python3-distutils

      - name: 5.下载IB
        working-directory: /workdir
        run: |
          df -hT $PWD
          wget https://github.com/sixleaves/buildOP4Six/releases/download/immortalwrt--202502191859--openwrt-24.10/immortalwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst -O immortalwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
          tar -I zstd -xvf immortalwrt-imagebuilder-x86-64.Linux-aarch64.tar.zst

      - name: 5.自定义固件
        working-directory: /workdir
        run: |
          cd immortalwrt-imagebuilder-x86-64.Linux-x86_64
          echo -e "$(nproc) thread compile"
          make image PROFILE="generic" PACKAGES="-mtd" -j$(nproc)

      - name: 6.上传bin目录
        uses: actions/upload-artifact@master
        with:
          name: amd64_x86
          path: immortalwrt/bin/targets/x86/64

      - name: 7.发布固件
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.FIRMWARE_NAME }}--${{ env.FILE_DATE }}--${{ env.REPO_BRANCH }}"
          artifacts: "immortalwrt/bin/targets/x86/64/*"
          body: |
            ImmortalWRT Version: ${{ env.REPO_BRANCH }}
            IP: 192.168.31.1 | Password: none