name: BuildAmd64
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 16 * *'

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt.git
  CONFIG_FILE: .config_amd64
  REPO_NAME: immortalwrt
  FIRMWARE_NAME: immortalwrt
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 1.下载config配置
        uses: actions/checkout@master

      - name: 2.安装依赖
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo apt install build-essential libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3

      - name: 3.下载IB
        working-directory: /workdir
        run: |
          df -hT $PWD
          wget https://github.com/sixleaves/buildOP4Six/releases/download/immortalwrt--202502191859--openwrt-24.10/immortalwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst -O immortalwrt-imagebuilder-x86-64.Linux-x86_64.tar.zst
          tar -I zstd -xvf immortalwrt-imagebuilder-x86-64.Linux-aarch64.tar.zst

      - name: 5.自定义固件
        working-directory: /workdir
        run: |
          cd immortalwrt-imagebuilder-x86-64.Linux-x86_64
          echo -e "$(nproc) thread compile"
          make image PROFILE="generic" PACKAGES="-mtd" -j$(nproc)

      - name: 6.上传bin目录
        uses: actions/upload-artifact@master
        with:
          name: amd64_x86
          path: immortalwrt/bin/targets/x86/64

      - name: 7.发布固件
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ env.FIRMWARE_NAME }}--${{ env.FILE_DATE }}--${{ env.REPO_BRANCH }}"
          artifacts: "immortalwrt/bin/targets/x86/64/*"
          body: |
            ImmortalWRT Version: ${{ env.REPO_BRANCH }}
            IP: 192.168.31.1 | Password: none